name: sync-fork
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME && git remote add upstream $REMOTE_REPO && git fetch --tags upstream && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          REMOTE_REPO: 'git@github.com:jxxghp/MoviePilot.git'
